// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb_qS9ogxghr9otCi_Fh7c5ZObw-7Z5qE',
    appId: '1:850527707211:web:92347c7c39da32d4c1edce',
    messagingSenderId: '850527707211',
    projectId: 'final-app-cb5ab',
    authDomain: 'final-app-cb5ab.firebaseapp.com',
    storageBucket: 'final-app-cb5ab.firebasestorage.app',
    measurementId: 'G-R41M675YR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlePM2648emYwsBkClFN0bMUkFkZsrcZ4',
    appId: '1:850527707211:android:cedcabac1edad3e9c1edce',
    messagingSenderId: '850527707211',
    projectId: 'final-app-cb5ab',
    storageBucket: 'final-app-cb5ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWSft-sWwVhRGeRpsQieus0CIDMAfFSdM',
    appId: '1:850527707211:ios:96210ab2b4bf3d98c1edce',
    messagingSenderId: '850527707211',
    projectId: 'final-app-cb5ab',
    storageBucket: 'final-app-cb5ab.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWSft-sWwVhRGeRpsQieus0CIDMAfFSdM',
    appId: '1:850527707211:ios:96210ab2b4bf3d98c1edce',
    messagingSenderId: '850527707211',
    projectId: 'final-app-cb5ab',
    storageBucket: 'final-app-cb5ab.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb_qS9ogxghr9otCi_Fh7c5ZObw-7Z5qE',
    appId: '1:850527707211:web:c1c7bfbd26572dd6c1edce',
    messagingSenderId: '850527707211',
    projectId: 'final-app-cb5ab',
    authDomain: 'final-app-cb5ab.firebaseapp.com',
    storageBucket: 'final-app-cb5ab.firebasestorage.app',
    measurementId: 'G-PD32G4YDFF',
  );

}